### ISSUE TITLE
No Data in https://zenodo.org/record/814831#.YDS94egzaUl

### ISSUE THREAD

**Issue by matt-audio** [sharathadavanne/multichannel-sed-crnn#10]
I download the data in website: https://zenodo.org/record/814831#.YDS94egzaUl
But there is only "audio/street" wav file inside.  No other data such as  "evaluation_setup" or other event wav. 
Do I need to download in other place? or? 

Looking forward your reply..

BR
Matt

**Comment by sharathadavanne** [comment]
Hi @matt-audio you will have to download all the four files in the link you shared. The 'evaluation_setup' folder is under the *_meta.zip file
