### ISSUE TITLE
How to test the trained model?

### ISSUE THREAD

**Issue by JingpengSun** [sharathadavanne/multichannel-sed-crnn#4]
Hi, I did find how to test one .h5 trained model by running sed.py?

**Comment by sharathadavanne** [comment]
Hi, I have only provided training scripts here, which learns from the training split and predicts on the validation split. If you want to test the trained model on a different dataset, then you will have to first load the trained model and test it with the corresponding features similar to[ this line](https://github.com/sharathadavanne/sed-crnn/blob/da81004c759e5471a22ed287cb95d7105dd7b9f6/sed.py#L160)

**Comment by JingpengSun** [comment]
Sorry for the late reply, I made it by following your answer, thank you!
And I have an another question: should we must train the network from scratch on our own data?

**Comment by sharathadavanne** [comment]
Yes, you will have to train it yourself. Also note, this model is tuned for [the DCASE 2017 SED dataset](https://zenodo.org/record/814831#.Ws2xO3VuYUE). If you are training on any other dataset, you might have to tune the model parameters (# layers, # filters/units/nodes per layer etc.)

**Comment by JingpengSun** [comment]
Oh, I see! I trained a model on our own dataset directly and got a terrible performance.
I will explore the model further more and tune the model parameters.
Many thanks~ I close it~
